spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
  application:
    name: mail
  mail:
    host: smtp.naver.com
    port: ${MAIL_PORT}
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: finalProject
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9292